### ISSUE TITLE
您好，构建博客可以不要原封不要引用我的博客一堆东西吗？

### ISSUE THREAD

**Issue by Gasolcloudteam** [zhang05lei20/zhang05lei20.github.io#1]
![Clip_2024-10-17_15-07-22](https://github.com/user-attachments/assets/8893eacb-6226-4d39-b861-b419c7a93d59)
![image](https://github.com/user-attachments/assets/b2954516-7a79-4bb9-9f7b-91095acd1a7e)
使用没问题，但是好歹改成你自己的吧哥们

**Comment by zhang05lei20** [comment]
不好意思，昨天在gitee拉下来，还没弄，我等会删除
&nbsp;


╰下辈子我要做一片海
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月17日(星期四) 下午3:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [zhang05lei20/zhang05lei20.github.io] 您好，构建博客可以不要原封不要引用我的博客一堆东西吗？ (Issue #1)














 
Clip_2024-10-17_15-07-22.png (view on web)
 image.png (view on web)
 使用没问题，但是好歹改成你自己的吧哥们

**Comment by zhang05lei20** [comment]
已删除
